---
name: Docker update stable tag

# Links/updates stable docker tags to specified version.
# This should be used after building a specific tagged image e.g. `:v0.7.2`.
#
#   dolfinx/dolfinx:stable
#   dolfinx/lab:stable
#   dolfinx/dev-env:stable
#   dolfinx/dolfinx-onbuild:stable

on:
  workflow_dispatch:
    inputs:
      end-user-tag:
        description: "Link dolfinx/lab/dolfinx-onbuild:stable to :end-user-tag"
        type: string
        required: true
      dev-env-tag:
        description: "Link dev-env:stable to :dev-env-tag"
        type: string
        required: true

jobs:
  update_stable_tag:
    name: Update stable tags
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install regctl
        run: |
          wget -O ./regctl https://github.com/regclient/regclient/releases/download/v0.10.0/regctl-linux-amd64
          chmod +x ./regctl

      - name: "Link :end-user-tag to :stable"
        run: |
           ./regctl image copy dolfinx/dolfinx:${{ inputs.end-user-tag }} dolfinx/dolfinx:stable
           ./regctl image copy dolfinx/lab:${{ inputs.end-user-tag }} dolfinx/lab:stable
           ./regctl image copy dolfinx/dolfinx-onbuild:${{ inputs.end-user-tag }} dolfinx/dolfinx-onbuild:stable
           # ghcr.io
           ./regctl image copy ghcr.io/fenics/dolfinx/dolfinx:${{ inputs.end-user-tag }} ghcr.io/fenics/dolfinx/dolfinx:stable
           ./regctl image copy ghcr.io/fenics/dolfinx/lab:${{ inputs.end-user-tag }} ghcr.io/fenics/dolfinx/lab:stable
           ./regctl image copy ghcr.io/fenics/dolfinx/dolfinx-onbuild:${{ inputs.end-user-tag }} ghcr.io/fenics/dolfinx/dolfinx-onbuild:stable
          
      - name: "Link :dev-env-tag to :stable"
           ./regctl image copy dolfinx/dev-env:${{ inputs.dev-env-tag }} dolfinx/dev-env:stable
           ./regctl image copy ghcr.io/fenics/dolfinx/dev-env:${{ inputs.dev-env-tag }} ghcr.io/fenics/dolfinx/dev-env:stable
