name: Build and push Docker CI test image

on:
  push:
    branches:
      - "*"
    # branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 0,3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker build --file .github/workflows/Dockerfile --target test --tag fenicsproject/test-env .
    - name: Login to DockerHub registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push DockerHub registry
      run: docker push fenicsproject/test-env
