---
name: Link stable Docker tag

# Links stable docker tag to specified version.
#
# This should be used after building a specific version of Docker.

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "link stable to this tag"
        type: string
        required: true

jobs:
  update_stable_tag:
    name: Update stable tags
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install regclient
        run: |
          wget -O regctl https://github.com/regclient/regclient/releases/download/v0.5.4/regctl-linux-amd64
          chmod +x regctl

      - name: Link supplied tag to stable on docker.io
        run: |
           regctl image copy dolfinx/dolfinx:${{ github.event.input.tag }} dolfinx/dolfinx:stable 
           regctl image copy dolfinx/lab:${{ github.event.input.tag }} dolfinx/lab:stable 
           regctl image copy dolfinx/dev-env:${{ github.event.input.tag }} dolfinx/dev-env:stable 
           regctl image copy dolfinx/dolfinx-onbuild:${{ github.event.input.tag }} dolfinx/dolfinx-onbuild:stable
      
      - name: Link supplied tag to stable on ghcr.io
        run: |
           regctl image copy ghcr.io/fenics/dolfinx/dolfinx:${{ github.event.input.tag }} ghcr.io/fenics/dolfinx/dolfinx:stable 
           regctl image copy ghcr.io/fenics/dolfinx/lab:${{ github.event.input.tag }} ghcr.io/fenics/dolfinx/lab:stable 
           regctl image copy ghcr.io/fenics/dolfinx/dev-env:${{ github.event.input.tag }} ghcr.io/fenics/dolfinx/dev-env:stable 
           regctl image copy ghcr.io/dolfinx/dolfinx-onbuild:${{ github.event.input.tag }} ghcr.io/fenics/dolfinx/dolfinx-onbuild:stable
